; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Quản Lý Nhà Trọ"
#define MyAppVersion "1.0"
#define MyAppPublisher "ADC Company, Inc."
#define MyAppURL "http://www.Friendlyteam.com/"
#define MyAppExeName "QuanLyNhaTro.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{05C4C998-AB7F-4D5C-9943-EF2A6C365897}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\quyentruycap1.txt
InfoAfterFile=C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\thongtinungdung.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist
OutputBaseFilename=setup
SetupIconFile=C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\ico.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\QuanLyNhaTro.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\ico.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\QuanLyNhaTro_test.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\quyentruycap1.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\README.TXT"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Admin\Documents\NetBeansProjects\my-project\QuanLyNhaTro_test\dist\thongtinungdung.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

