/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import help.General;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    static String name = "", role = "";

    public MainFrame(String name, String role) {
        initComponents();
        this.name = name;
        this.role = role;
        init();
        clock();
        setStatus(true);
    }

    void init() {
        setLocationRelativeTo(this);
        setIconImage(General.AppIcon());
        lblName.setText(role + ": " + name);
        if(role=="Employer"){
            mitTKDT.setEnabled(false);
            mitNV.setEnabled(false);
        }
    }

    public void clock() {
        Thread clock = new Thread() {
            @Override
            public void run() {
                while (true) {
                    Date now = new Date();
                    SimpleDateFormat formater = new SimpleDateFormat();
                    formater.applyPattern("hh:mm:ss aa");
                    String time = formater.format(now);
                    lblTime.setText(time);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
        clock.start();
    }

    void setStatus(boolean isEnable) {
        btnTP.setEnabled(isEnable);
        btnDG.setEnabled(isEnable);
        btnDX.setEnabled(isEnable);
        btnDN.setEnabled(!isEnable);
        btnHopDong.setEnabled(isEnable);
        mitDMK.setEnabled(isEnable);
        mitDX.setEnabled(isEnable);
        mitDN.setEnabled(!isEnable);
        mnuQL.setEnabled(isEnable);
        mnuTK.setEnabled(isEnable);
    }

    public void logout() {
        General.logOff();
        setStatus(false);
        LoginDiglog lg = new LoginDiglog();
        lg.newLogin = true;
        lg.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTP = new javax.swing.JButton();
        btnHopDong = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnDG = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnDN = new javax.swing.JButton();
        btnDX = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDN = new javax.swing.JMenuItem();
        mitDX = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mitDMK = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuQL = new javax.swing.JMenu();
        mitNT = new javax.swing.JMenuItem();
        mitNV = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mitHopDong = new javax.swing.JMenuItem();
        mnuTK = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mitTKDG = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mitTKDT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TimPhongTro");
        setResizable(false);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnTP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Prefab_House_24px.png"))); // NOI18N
        btnTP.setText("Tìm phòng");
        btnTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTP.setFocusable(false);
        btnTP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTP.setIconTextGap(8);
        btnTP.setMargin(new java.awt.Insets(18, 14, 18, 14));
        btnTP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        btnTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTP);

        btnHopDong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Agreement_24px_1.png"))); // NOI18N
        btnHopDong.setText("Hợp đồng ");
        btnHopDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHopDong.setFocusable(false);
        btnHopDong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHopDong.setIconTextGap(8);
        btnHopDong.setMargin(new java.awt.Insets(18, 14, 18, 14));
        btnHopDong.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Notes.png"))); // NOI18N
        btnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHopDong);
        jToolBar1.add(jSeparator7);

        btnDG.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Christmas_Star_24px_1.png"))); // NOI18N
        btnDG.setText("Đánh giá   ");
        btnDG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDG.setFocusable(false);
        btnDG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDG.setIconTextGap(8);
        btnDG.setMargin(new java.awt.Insets(18, 14, 18, 14));
        btnDG.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Favourites.png"))); // NOI18N
        btnDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDG);
        jToolBar1.add(jSeparator6);

        btnDN.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_2_24px_2.png"))); // NOI18N
        btnDN.setText("Đăng nhập");
        btnDN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDN.setFocusable(false);
        btnDN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDN.setIconTextGap(8);
        btnDN.setMargin(new java.awt.Insets(18, 14, 18, 14));
        btnDN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Open lock.png"))); // NOI18N
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDN);

        btnDX.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lock.png"))); // NOI18N
        btnDX.setText("Đăng xuất");
        btnDX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDX.setFocusable(false);
        btnDX.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDX.setIconTextGap(8);
        btnDX.setMargin(new java.awt.Insets(18, 14, 18, 14));
        btnDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDX);
        jToolBar1.add(jSeparator9);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_24px.png"))); // NOI18N
        jButton7.setText("Hướng dẫn");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(8);
        jButton7.setMargin(new java.awt.Insets(18, 14, 18, 14));
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Globe.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator8);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_24px.png"))); // NOI18N
        jButton3.setText("Kết thúc   ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setIconTextGap(8);
        jButton3.setMargin(new java.awt.Insets(18, 14, 18, 14));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTime.setText("Time");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Info.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Alarm.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Group 4 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblTime)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(lblTime))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("UTM Cabaret", 0, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Welcome to our application");

        lblName.setFont(new java.awt.Font("UTM Dinh Tran", 0, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 169, 0));
        lblName.setText("Name");

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 0, 10, 0));
        jMenuBar1.setOpaque(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 38));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mitDN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mitDN.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_2_24px_2.png"))); // NOI18N
        mitDN.setText("Đăng nhập");
        mitDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDNActionPerformed(evt);
            }
        });
        jMenu1.add(mitDN);

        mitDX.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mitDX.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lock.png"))); // NOI18N
        mitDX.setText("Đăng xuất");
        mitDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDXActionPerformed(evt);
            }
        });
        jMenu1.add(mitDX);
        jMenu1.add(jSeparator1);

        mitDMK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shield.png"))); // NOI18N
        mitDMK.setText("Đổi mật khẩu");
        mitDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDMK);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_24px.png"))); // NOI18N
        jMenuItem4.setText("Kết thúc");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        mnuQL.setText("Quản lý");
        mnuQL.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuQL.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mitNT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mitNT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitNT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Users.png"))); // NOI18N
        mitNT.setText("Người thuê");
        mitNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNTActionPerformed(evt);
            }
        });
        mnuQL.add(mitNT);

        mitNV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mitNV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User.png"))); // NOI18N
        mitNV.setText("Nhân viên");
        mitNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNVActionPerformed(evt);
            }
        });
        mnuQL.add(mitNV);
        mnuQL.add(jSeparator11);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Brick house.png"))); // NOI18N
        jMenuItem6.setText("Loại nhà trọ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuQL.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home.png"))); // NOI18N
        jMenuItem7.setText("Phòng trọ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuQL.add(jMenuItem7);
        mnuQL.add(jSeparator3);

        mitHopDong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mitHopDong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Notes.png"))); // NOI18N
        mitHopDong.setText("Hợp đồng");
        mitHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHopDongActionPerformed(evt);
            }
        });
        mnuQL.add(mitHopDong);

        jMenuBar1.add(mnuQL);

        mnuTK.setText("Thống kê");
        mnuTK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuTK.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User group.png"))); // NOI18N
        jMenuItem9.setText("Người thuê từng năm");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnuTK.add(jMenuItem9);
        mnuTK.add(jSeparator4);

        mitTKDG.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mitTKDG.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mitTKDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Favourites.png"))); // NOI18N
        mitTKDG.setText("Đánh giá nhà trọ");
        mitTKDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTKDGActionPerformed(evt);
            }
        });
        mnuTK.add(mitTKDG);
        mnuTK.add(jSeparator10);

        mitTKDT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mitTKDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mitTKDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dollar.png"))); // NOI18N
        mitTKDT.setText("Doanh thu");
        mitTKDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTKDTActionPerformed(evt);
            }
        });
        mnuTK.add(mitTKDT);

        jMenuBar1.add(mnuTK);

        jMenu4.setText("Trợ giúp");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 10, 0, 0));

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Globe.png"))); // NOI18N
        jMenuItem11.setText("Hướng dẫn");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);
        jMenu4.add(jSeparator5);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Info.png"))); // NOI18N
        jMenuItem12.setText("Giới thiệu");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)
                        .addGap(18, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDXActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_mitDXActionPerformed

    private void mitDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDMKActionPerformed
        // TODO add your handling code here:\
        new DoiMatKhauDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mitDMKActionPerformed

    private void btnDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGActionPerformed
        // TODO add your handling code here:
        new DanhGiaFrame().setVisible(true);
    }//GEN-LAST:event_btnDGActionPerformed

    private void btnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDongActionPerformed
        // TODO add your handling code here:
        new HopDongFrame().setVisible(true);
    }//GEN-LAST:event_btnHopDongActionPerformed

    private void btnTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPActionPerformed
        // TODO add your handling code here:
        new TimPhongDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnTPActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        new LoginDiglog().setVisible(true);
    }//GEN-LAST:event_btnDNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(this, "Are you sure to exit?");
        if (click == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mitNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNTActionPerformed
        // TODO add your handling code here:
        new NguoiThueFrame().setVisible(true);
    }//GEN-LAST:event_mitNTActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new LoaiNhaTroFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new PhongTroFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mitHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHopDongActionPerformed
        // TODO add your handling code here:
        new HopDongFrame().setVisible(true);
    }//GEN-LAST:event_mitHopDongActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new HuongDanDialog(this, true).setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXActionPerformed
        // TODO add your handling code here:
       this.logout();
    }//GEN-LAST:event_btnDXActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ThongKeFrame tk = new ThongKeFrame();
        tk.tabIndex = 0;
        tk.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mitTKDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTKDGActionPerformed
        // TODO add your handling code here:
        ThongKeFrame tk = new ThongKeFrame();
        tk.tabIndex = 1;
        tk.setVisible(true);
    }//GEN-LAST:event_mitTKDGActionPerformed

    private void mitTKDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTKDTActionPerformed
        // TODO add your handling code here:
        ThongKeFrame tk = new ThongKeFrame();
        tk.tabIndex = 2;
        tk.setVisible(true);
    }//GEN-LAST:event_mitTKDTActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new HuongDanDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new GioithieuDialog().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(this, "Are you sure to exit?");
        if (click == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mitDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDNActionPerformed
        // TODO add your handling code here:
        new LoginDiglog().setVisible(true);
    }//GEN-LAST:event_mitDNActionPerformed

    private void mitNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNVActionPerformed
        // TODO add your handling code here:
        new NguoiQuanLyFrame().setVisible(true);
    }//GEN-LAST:event_mitNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(name, role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDG;
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnDX;
    private javax.swing.JButton btnHopDong;
    private javax.swing.JButton btnTP;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mitDMK;
    private javax.swing.JMenuItem mitDN;
    private javax.swing.JMenuItem mitDX;
    private javax.swing.JMenuItem mitHopDong;
    private javax.swing.JMenuItem mitNT;
    private javax.swing.JMenuItem mitNV;
    private javax.swing.JMenuItem mitTKDG;
    private javax.swing.JMenuItem mitTKDT;
    private javax.swing.JMenu mnuQL;
    private javax.swing.JMenu mnuTK;
    // End of variables declaration//GEN-END:variables
}
